export default {
    enroute: {
        airports: 'http://api.flyskyline.gov.cn:8087/efb-v2/enroute/nav/chunk-1.db',
        vors: 'http://api.flyskyline.gov.cn:8087/efb-v2/enroute/nav/chunk-2.db',
        ndbs: 'http://api.flyskyline.gov.cn:8087/efb-v2/enroute/nav/chunk-3.db',
        waypoints: 'http://api.flyskyline.gov.cn:8087/efb-v2/enroute/nav/chunk-4.db',
        airways: 'http://api.flyskyline.gov.cn:8087/efb-v2/enroute/nav/chunk-5.db',
        firs: 'http://api.flyskyline.gov.cn:8087/efb-v2/enroute/nav/chunk-6.db',
        grid: 'http://api.flyskyline.gov.cn:8087/efb-v2/enroute/nav/world-terrain.db',
        tilemap: 'http://api.flyskyline.gov.cn:8087/efb-v2/enroute/aip'
    },
    enrouteQuery: 'http://api.flyskyline.gov.cn:8087/efb-v2/enroute/query',
    enrouteSearch: 'http://api.flyskyline.gov.cn:8087/efb-v2/enroute/search',
    search:'http://api.flyskyline.gov.cn:8087/efb-v2/navdata/search',
    weather: 'http://api.flyskyline.gov.cn:8087/efb-v2/database/getWeather',
    notam: 'http://api.flyskyline.gov.cn:8087/efb-v2/database/getNOTAM',
    airport: 'http://api.flyskyline.gov.cn:8087/efb-v2/database/getAirport',
    jeppesenCharts: 'http://api.flyskyline.gov.cn:8087/efb-v2/charts/jeppesen/chartList',
    aipCharts: 'http://api.flyskyline.gov.cn:8087/efb-v2/charts/aip/chartList',
    jeppesenUrl: 'http://api.flyskyline.gov.cn:8087/efb-v2/charts/jeppesen/charturl',
    aipUrl: 'http://api.flyskyline.gov.cn:8087/efb-v2/charts/aip/charturl',
    airportCom:'http://api.flyskyline.gov.cn:8087/efb-v2/database/getCommunication',
    routeFinder:'http://api.flyskyline.gov.cn:8087/efb-v2/route/findRoute',
    parseSelfRoute:'http://api.flyskyline.gov.cn:8087/efb-v2/route/selfRoute',
    aircraftConfig: 'http://api.flyskyline.gov.cn:8087/efb-v2/database/getAircraftConfig',
    runways: 'http://api.flyskyline.gov.cn:8087/efb-v2/database/getRunways',
    procedure: 'http://api.flyskyline.gov.cn:8087/efb-v2/database/getProcedures',
    apps: 'http://api.flyskyline.gov.cn:8087/efb-v2/database/getAPPs',
    getFlights: 'http://api.flyskyline.gov.cn:8087/efb-v2/user/getFlights',
    updateFlights: 'http://api.flyskyline.gov.cn:8087/efb-v2/user/updateFlights',
    deleteFlights: 'http://api.flyskyline.gov.cn:8087/efb-v2/user/deleteFlight',
    uploadTempFlight: 'http://api.flyskyline.gov.cn:8087/efb-v2/user/upload',
    getTempFlight: 'http://api.flyskyline.gov.cn:8087/efb-v2/user/getTempFlights',
    deleteTempFlight: 'http://api.flyskyline.gov.cn:8087/efb-v2/user/unloadFlights',
    ownship: 'https://api.skylineflyleague.cn/map-api-v2/online',
    getPinboard: 'http://api.flyskyline.gov.cn:8087/efb-v2/user/getPinboard',
    uploadPinboard: 'http://api.flyskyline.gov.cn:8087/efb-v2/user/pinboardEvent',
    uploadWaypoint: 'http://api.flyskyline.gov.cn:8087/efb-v2/user/waypoint',
    navLink: 'http://api.flyskyline.gov.cn:8087/efb-v2/user/navlink',
    waypoint: 'http://api.flyskyline.gov.cn:8087/efb-v2/user/getWaypoint',
    login: 'http://api.flyskyline.gov.cn:8087/efb-v2/OAuth2.0/authorize',
    points: 'http://api.flyskyline.gov.cn:8087/efb-v2/user/useUserIntegral',
    uploadFile: 'http://api.flyskyline.gov.cn:8087/efb-v2/user/upload',
    weatherRadar: 'https://api.rainviewer.com/public/weather-maps.json',
    simbrief: 'https://www.simbrief.com/api/xml.fetcher.php',
    airac: 'http://api.flyskyline.gov.cn:8087/efb-v2/airac?get=current'
}